---
title: "Test Scores"
author: "Charlotte Lopp"
date: "February 22, 2018"
output: html_document
---

```{r load-libraries, message = FALSE, echo = FALSE}
# load general-use packages
library("dplyr")
library("tidyr")
library("knitr")
library("ggplot2")
library("ggthemes")
library("kableExtra")
```

```{r setup-training-scores, echo = FALSE}
# This downloads the csv files with our data
# into our project directory
#ten <- read.csv(paste0("data/",
#                                "Users-Export-2018-February-17-0220.csv"),
#                                header = TRUE,
#                                stringsAsFactors = FALSE)

#twenty <- read.csv(paste0("data/",
#                                "Users-Export-2018-February-17-0931.csv"),
#                                header = TRUE,
#                                stringsAsFactors = FALSE)

#thirty <- read.csv(paste0("data/",
#                                "Users-Export-2018-February-18-0228.csv"),
#                                header = TRUE,
#                                stringsAsFactors = FALSE)

#forty <- read.csv(paste0("data/",
#                                "Users-Export-2018-February-18-1732.csv"),
#                                header = TRUE,
#                                stringsAsFactors = FALSE)

#fifty <- read.csv(paste0("data/",
#                                "Users-Export-2018-February-18-2039.csv"),
#                                header = TRUE,
#                                stringsAsFactors = FALSE)

#sixty <- read.csv(paste0("data/",
#                                "Users-Export-2018-February-19-0036.csv"),
#                                header = TRUE,
#                                stringsAsFactors = FALSE)

#use_ten <- subset(ten, select = -c(X_trainings_0_training_score,
#                                   X_trainings_1_training_score,
#                                   X_trainings_2_training_score,
#                                   X_trainings_3_training_score,
#                                   X_trainings_4_training_score,
#                                   X_trainings_5_training_score,
#                                   X_trainings_6_training_score,
#                                   X_trainings_7_training_score,
#                                   X_trainings_8_training_score,
#                                   X_trainings_9_training_score,
#                                   X_trainings_10_training_score))

#use_twenty <- subset(twenty, select = -c(X_trainings_11_training_score,
#                                   X_trainings_12_training_score,
#                                   X_trainings_13_training_score,
#                                   X_trainings_14_training_score,
#                                   X_trainings_15_training_score,
#                                   X_trainings_16_training_score,
#                                   X_trainings_17_training_score,
#                                   X_trainings_18_training_score,
#                                   X_trainings_19_training_score,
#                                   X_trainings_20_training_score))

#use_thirty <- subset(thirty, select = -c(X_trainings_21_training_score,
#                                   X_trainings_22_training_score,
#                                   X_trainings_23_training_score,
#                                   X_trainings_24_training_score,
#                                   X_trainings_25_training_score,
#                                   X_trainings_26_training_score,
#                                   X_trainings_27_training_score,
#                                   X_trainings_28_training_score,
#                                   X_trainings_29_training_score,
#                                   X_trainings_30_training_score))

#use_forty <- subset(forty, select = -c(X_trainings_31_training_score,
#                                   X_trainings_32_training_score,
#                                   X_trainings_33_training_score,
#                                   X_trainings_34_training_score,
#                                   X_trainings_35_training_score,
#                                   X_trainings_36_training_score,
#                                   X_trainings_37_training_score,
#                                   X_trainings_38_training_score,
#                                   X_trainings_39_training_score,
#                                   X_trainings_40_training_score))

#use_fifty <- subset(fifty, select = -c(X_trainings_41_training_score,
#                                   X_trainings_42_training_score,
#                                   X_trainings_43_training_score,
#                                   X_trainings_44_training_score,
#                                   X_trainings_45_training_score,
#                                   X_trainings_46_training_score,
#                                   X_trainings_47_training_score,
#                                   X_trainings_48_training_score,
#                                   X_trainings_49_training_score,
#                                   X_trainings_50_training_score))

#use_sixty <- subset(sixty, select = -c(X_trainings_51_training_score,
#                                   X_trainings_52_training_score,
#                                   X_trainings_53_training_score,
#                                   X_trainings_54_training_score,
#                                   X_trainings_55_training_score,
#                                   X_trainings_56_training_score,
#                                   X_trainings_57_training_score,
#                                   X_trainings_58_training_score,
#                                   X_trainings_59_training_score))
```

```{r setup-training-history, echo = FALSE}
# This downloads the csv files with our data
# into our project directory
FACS <- read.csv(paste0("data/",
                                "FACS-training-history.csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

SETT <- read.csv(paste0("data/",
                                "SETT-training-history.csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

METT <- read.csv(paste0("data/",
                                "METT-training-history.csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

RETT_F <- read.csv(paste0("data/",
                                "RETT-Family-training-history.csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

RETT_LE <- read.csv(paste0("data/",
                                "RETT-LE-training-history.csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

RETT_W <- read.csv(paste0("data/",
                                "RETT-Workplace-training-history.csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

data <- read.csv(paste0("data/",
                                "register-2018-02-23 (1).csv"),
                                header = TRUE,
                                stringsAsFactors = FALSE)

use_FACS <- subset(FACS, select = -c(user_login, country, training_id, timespan))

use_SETT <- subset(SETT, select = -c(user_login, country, training_id, timespan))

use_METT <- subset(METT, select = -c(user_login, country, training_id, timespan))

use_RETT_F <- subset(RETT_F, select = -c(user_login, country, training_id, timespan))

use_RETT_LE <- subset(RETT_LE, select = -c(user_login, country, training_id, timespan))

use_RETT_W <- subset(RETT_W, select = -c(user_login, country, training_id, timespan))
```

## Training History of Tools: FACS
```{r FACS, fig.height = 20, fig.width = 22, echo = FALSE}
# This looks at the trend of training tool score
# by customer for FACS
FACS_ID <- use_FACS %>%
  group_by(user_id) %>%
  unique()

FACS_ID %>%
  group_by(user_id, date_taken, score) %>%
  ggplot(aes(x = date_taken,
             y = score,
             color = user_id)) +
  geom_point(size = 1) +
  facet_wrap( ~ user_id) +
  xlab("Date") +
  ylab("Score")
```

```{r FACS-number-of-times-taken, echo = FALSE}
# This looks at the number of times FACS is taken
# on average by customers
FACS_ID %>%
  group_by(user_id) %>%
  tally() %>%
  summarize(mean_count = mean(n)) %>%
  kable("html") %>%
  kable_styling()
  
```

```{r FACS-average-score, echo = FALSE}
FACS_ID %>%
  group_by(training) %>%
  summarize(mean_score = mean(score)) %>%
  kable("html") %>%
  kable_styling()
```

```{r combine-two-dataframes-FACS-and-data, echo = FALSE}
# I changed the name of the column names using
#  names(df)[names(df) == 'old.var.name'] <- 'new.var.name'
total_FACS <- merge(FACS_ID, data, by = "user_email")
```

## Training History of Tools: SETT
```{r SETT, echo = FALSE}
# This looks at the trend of training tool score
# by customer for SETT
SETT_ID <- use_SETT %>%
  group_by(user_id) %>%
  unique()

SETT_ID %>%
  group_by(user_id, date_taken, score) %>%
  ggplot(aes(x = date_taken,
             y = score,
             color = user_id)) +
  geom_point(size = 1) +
  xlab("Date") +
  ylab("Score")
```

```{r SETT-number-of-times-taken, echo = FALSE}
# This looks at the number of times SETT is taken
# on average by customers
SETT_ID %>%
  group_by(user_id) %>%
  tally() %>%
  summarize(mean_count = mean(n)) %>%
  kable("html") %>%
  kable_styling()
  
```

```{r SETT-average-score, echo = FALSE}
SETT_ID %>%
  group_by(training) %>%
  summarize(mean_score = mean(score)) %>%
  kable("html") %>%
  kable_styling()
```

```{r combine-two-dataframes-SETT-and-data, echo = FALSE}
# I changed the name of the column names using
#  names(df)[names(df) == 'old.var.name'] <- 'new.var.name'
total_SETT <- merge(SETT_ID, data, by = "user_email")
```

## Training History of Tools: METT
```{r METT, echo = FALSE}
# This looks at the trend of training tool score
# by customer for METT
METT_ID <- use_METT %>%
  group_by(user_id) %>%
  unique()

METT_ID %>%
  group_by(user_id, date_taken, score) %>%
  ggplot(aes(x = date_taken,
             y = score,
             color = user_id)) +
  geom_point(size = 1) +
  xlab("Date") +
  ylab("Score")
```

```{r METT-number-of-times-taken, echo = FALSE}
# This looks at the number of times METT is taken
# on average by customers
METT_ID %>%
  group_by(user_id) %>%
  tally() %>%
  summarize(mean_count = mean(n)) %>%
  kable("html") %>%
  kable_styling()
  
```

```{r METT-average-score, echo = FALSE}
METT_ID %>%
  group_by(training) %>%
  summarize(mean_score = mean(score)) %>%
  kable("html") %>%
  kable_styling()
```

```{r combine-two-dataframes-METT-and-data, echo = FALSE}
# I changed the name of the column names using
#  names(df)[names(df) == 'old.var.name'] <- 'new.var.name'
total_METT <- merge(METT_ID, data, by = "user_email")
```

## Trends Across all Tools
```{r combine-all-dataframes, echo = FALSE}
# I changed the name of the column names using
#  names(df)[names(df) == 'old.var.name'] <- 'new.var.name'
FACS_METT <- rbind(FACS_ID, METT_ID)

FACS_METT_SETT <- rbind(FACS_METT, SETT_ID)

total_tools <- merge(FACS_METT_SETT, data, by = "user_email")
```

```{r our-customer-base-by-occupation, echo = FALSE}
total_tools %>%
  group_by(occupationalStatus)
```
**Note:** This shows our customer base by occupation.